apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: windows-image-builder
spec:
  git_provider:
    secret:
      key: provider.token
      name: github-webhook-config
    webhook_secret:
      key: webhook.secret
      name: github-webhook-config
  url: https://github.com/ksimon1/windows-image-builder
