apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: windows-image-builder
  namespace: windows-builder
spec:
  git_provider:
    secret:
      key: provider.token
      name: github-webhook-config
    type: github
    url: https://github.com
    webhook_secret:
      key: webhook.secret
      name: github-webhook-config
  incoming:
  - secret:
      key: secret
      name: windows-rebuilder
    targets:
    - main
    type: webhook-url
  url: https://github.com/ksimon1/windows-image-builder
