apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: win10
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/target-namespace: "kubevirt"
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipelines/git-windows-bios-installer-pipeline.yaml]"
    pipelinesascode.tekton.dev/task-1: "git-clone"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/kubevirt-tekton-tasks-okd.yaml]"
spec:
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: autounattendConfigMapName
      value: windows10-bios-autounattend-test
    - name: virtioContainerDiskName
      value: 'quay.io/kubevirt/virtio-container-disk:v0.59.0'
    - name: sourceTemplateName
      value: windows10-desktop-large
    - name: sourceTemplateNamespace
      value: openshift
    - name: installerTemplateName
      value: windows10-desktop-large-installer
    - name: allowReplaceInstallerTemplate
      value: 'true'
    - name: baseDvName
      value: win10
    - name: baseDvNamespace
      value: kubevirt-os-images
    - name: isoDVName
      value: win10
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineRef:
    name: git-windows-bios-installer
  serviceAccountName: pipeline
  timeout: 2h0m0s
