apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: win10
  namespace: kubevirt
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/target-namespace: "kubevirt"
spec:
  params:
    - name: autounattendConfigMapName
      value: windows10-bios-autounattend-test
    - name: virtioContainerDiskName
      value: 'quay.io/kubevirt/virtio-container-disk:v0.59.0'
    - name: sourceTemplateName
      value: windows10-desktop-large
    - name: sourceTemplateNamespace
      value: openshift
    - name: installerTemplateName
      value: windows10-desktop-large-installer
    - name: allowReplaceInstallerTemplate
      value: 'true'
    - name: baseDvName
      value: win10
    - name: baseDvNamespace
      value: kubevirt-os-images
    - name: isoDVName
      value: win10
  pipelineRef:
    name: git-windows-bios-installer
  serviceAccountName: pipeline
  timeout: 2h0m0s
